name: flutter_pub_get_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.35+372

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ##############################################################################
  # Design UI/UX 设计规范
  ##############################################################################
  cupertino_icons: ^1.0.3

  ### 国际化支持 ###
  flutter_localizations:
    sdk: flutter
  # intl: ^0.17.0

  ### 字体库 ### 
  google_fonts: 2.1.0 # 可以删除

  ### 屏幕适配 ###
  flutter_screenutil: 5.1.0

  ##############################################################################
  # Google Firebase Flutter SDK 开发者套餐(BaaS)
  ##############################################################################
  ### 核心库, 提供基础功能/接口 ###
  firebase_core: ^1.7.0

  ### 应用埋点数据上报 ###
  firebase_analytics: ^8.3.4

  ### 应用错误日志/崩溃上报 ###
  firebase_crashlytics: ^2.3.0

  ### deep link ###
  firebase_dynamic_links: ^2.0.10

  ### 没有用到的 应用内推送 ### 
  firebase_messaging: ^10.0.8

  ### 对象存储 ###
  firebase_storage: ^10.2.10

  ### 数据库 ###
  cloud_firestore: ^2.5.4

  ### 云函数 ###
  cloud_functions: ^3.0.4

  # cloud_functions_web: ^4.0.13
  ### 性能监测 ###
  firebase_performance: ^0.8.0+11
  # firebase_performance_web: ^0.1.0+11

  ### 动态配置 ###
  firebase_remote_config: ^1.0.4

  ### 用户认证授权 ###
  firebase_auth: ^3.3.8 # Auth Provider
  google_sign_in: ^5.1.0 # Google Sign-In plugin
  sign_in_with_apple: ^3.2.0 # Apple Sign-In plugin
  flutter_facebook_auth: # Facebook Sign-In plugin
    git:
      url: https://github.com/darwin-morocho/flutter-facebook-auth.git
      ref: f95e99e33f0bb7d59bf0099a85d074b6dda724a9
      path: facebook_auth

  ###############################################################################
  # Statement Manager
  ###############################################################################
  provider: ^6.0.2

  # Router, State, Depencency injection
  get: ^4.3.8

  ###############################################################################
  # Persistence 数据持久化
  ###############################################################################
  # Hive 高性数据库, 目前仅用来做发送消息时候的状态存储(大才小用了)
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  # 用于存储 logs 日志
  localstorage: ^4.0.0+1

  # 存储 flags 状态
  shared_preferences: ^2.0.8

  ################################################################################
  # extending languages dart 语言功能扩展
  ################################################################################
  tuple: ^2.0.0 # 元组支持
  rxdart: ^0.27.2
  built_collection: ^5.1.1
  built_value: ^8.1.2

  ################################################################################
  # App 数据上报/统计/推广
  ################################################################################
  facebook_app_events: ^0.15.0
  appsflyer_sdk: ^6.5.2

  #################################################################################
  # Native libraries extending Flutter abilities 原生库扩展 Flutter 能力 
  #################################################################################
  ### 打开外部链接 ###
  url_launcher: ^6.1.0

  ### 应用评分 ###
  in_app_review: ^2.0.3

  ### 打开通知设置 ###
  open_app_settings: ^2.0.0

  ### 权限申请(图片保存) ###
  permission_handler: ^9.2.0

  ### 截图分享 ###
  flutter_screenshot_callback: ^0.0.8

  ### 应用未读小红点 ###
  flutter_app_badger: ^1.3.0

  ### 网络状态/环境 ###
  connectivity_plus: ^2.2.0

  ### 设备信息 ###
  device_info_plus: ^3.2.1
  package_info_plus: ^1.3.0

  ### 文件类型 ###
  mime_type: ^1.0.0

  ### Social Sharing 社媒分享 ###
  share_plus: ^3.1.0
  flutter_share_me:
    git:
      url: https://github.com/OpenFlutter/flutter_share_me.git
      ref: 70046e4ff74b13522066cde762abddba00b26a91

  ### Native View 组件 (原生视图扩展) ###
  webview_flutter: ^2.1.1
  video_player: ^2.3.0

  ### 应用内存储路径 ###
  path_provider: ^2.0.9

  ### 保存图片到相册 ###
  image_gallery_saver: ^1.7.1

  ### 选择图片 ###
  image_picker: ^0.8.4+1

  ### 震动 ###
  vibration: ^1.7.4-nullsafety.0

  ### 显示模式? ###
  flutter_displaymode: ^0.3.2

  #################################################################################
  # Flutter Widget/UI 扩展
  ################################################################################# 
  ### 应用内部 Toast 提醒 ### 
  bot_toast: ^4.0.1

  ### SVG 支持 ### 
  flutter_svg: ^0.22.0

  ### 图片缓存支持 ###
  cached_network_image: ^3.1.0

  ### 加载中对话框 ###
  flutter_easyloading: ^3.0.3

  ### 滑动卡片 ###
  card_swiper: ^2.0.1

  ### 应用内截图 ###
  screenshot: ^1.2.3

  ### 滚动组件下拉刷新/上拉加载 ###
  pull_to_refresh: ^2.0.0

  ### 滚动组件位置监听 ###
  inview_notifier_list:
    git:
      url: https://github.com/dreamer2q/inview_notifier_list

  badges: ^2.0.2
  flutter_linkify: ^5.0.2 
  flutter_slidable: 1.0.0-dev.9
  auto_size_text: ^3.0.0

  ###############################################################################
  # Flutter Animations 动画扩展
  ###############################################################################
  ### 复杂的矢量动画 ###
  lottie: ^1.2.1

  ### 2d 物理动画扩展 ###
  flame: ^1.0.0
  flame_forge2d: ^0.8.3

  ### 快速创建简单的动画 ###
  simple_animations: ^4.0.1

  ### 动效扩展 ###
  liquid_swipe:
    git: https://github.com/aboutmydreams/liquid_swipe_flutter.git

  ### GIF 动画(无法使用lottie时) ###  
  flutter_gifimage:
    git: https://github.com/aboutmydreams/flutter_gifimage.git

  ### 可以废弃的东西
  flutter_lorem: ^2.0.0
  event_bus: ^2.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^2.1.4
  built_value_generator: ^8.1.1
  cider: ^0.1.0
  flutter_lints: ^1.0.4
  hive_generator: ^1.1.1
  mockito: ^5.0.15
  flutter_native_splash: ^1.3.1

flutter_native_splash:
  color: "#ffffff"
  # image: assets/launch-750.png
  image: assets/images/3x.png
  android_gravity: fill
  ios_content_mode: scaleToFill
  android: true
  ios: true
  web: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
